name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: actions/setup-cmake@v3

    - name: Generate build files
      run: cmake -S . -B _build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build _build --config Release
      working-directory: _build

    - name: Run tests
      run: _build/test_app
      working-directory: _build
